//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 04:52:19 PM IST 
//


package org.wso2.developerstudio.htconfig.models;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.wso2.ht.schema.deployment.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HTDeploymentConfig_QNAME = new QName("http://wso2.org/ht/schema/deployment/config", "HTDeploymentConfig");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.wso2.ht.schema.deployment.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TCallback.Service }
     * 
     */
    public TCallback.Service createTCallbackService() {
        return new TCallback.Service();
    }

    /**
     * Create an instance of {@link THTDeploymentConfig }
     * 
     */
    public THTDeploymentConfig createTHTDeploymentConfig() {
        return new THTDeploymentConfig();
    }

    /**
     * Create an instance of {@link THTDeploymentConfig.Notification }
     * 
     */
    public THTDeploymentConfig.Notification createTHTDeploymentConfigNotification() {
        return new THTDeploymentConfig.Notification();
    }

    /**
     * Create an instance of {@link TPublish.Service }
     * 
     */
    public TPublish.Service createTPublishService() {
        return new TPublish.Service();
    }

    /**
     * Create an instance of {@link TPublish }
     * 
     */
    public TPublish createTPublish() {
        return new TPublish();
    }

    /**
     * Create an instance of {@link THTDeploymentConfig.Task }
     * 
     */
    public THTDeploymentConfig.Task createTHTDeploymentConfigTask() {
        return new THTDeploymentConfig.Task();
    }

    /**
     * Create an instance of {@link TCallback }
     * 
     */
    public TCallback createTCallback() {
        return new TCallback();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link THTDeploymentConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wso2.org/ht/schema/deployment/config", name = "HTDeploymentConfig")
    public JAXBElement<THTDeploymentConfig> createHTDeploymentConfig(THTDeploymentConfig value) {
        return new JAXBElement<THTDeploymentConfig>(_HTDeploymentConfig_QNAME, THTDeploymentConfig.class, null, value);
    }

}
