//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 04:52:19 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(xmlns = { 
	      @javax.xml.bind.annotation.XmlNs(prefix = "hic", 
	                 namespaceURI="http://wso2.org/ht/schema/deployment/config")},namespace = "http://wso2.org/ht/schema/deployment/config", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.wso2.developerstudio.htconfig.models;
