//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.15 at 04:52:19 PM IST 
//


package org.wso2.developerstudio.htconfig.models;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for tHTDeploymentConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tHTDeploymentConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="task" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="publish" type="{http://wso2.org/ht/schema/deployment/config}tPublish"/>
 *                   &lt;element name="callback" type="{http://wso2.org/ht/schema/deployment/config}tCallback"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="notification" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="publish" type="{http://wso2.org/ht/schema/deployment/config}tPublish"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tHTDeploymentConfig", propOrder = {
    "task",
    "notification"
})
public class THTDeploymentConfig {

    protected List<THTDeploymentConfig.Task> task;
    protected List<THTDeploymentConfig.Notification> notification;

    /**
     * Gets the value of the task property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the task property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTask().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link THTDeploymentConfig.Task }
     * 
     * 
     */
    public List<THTDeploymentConfig.Task> getTask() {
        if (task == null) {
            task = new ArrayList<THTDeploymentConfig.Task>();
        }
        return this.task;
    }

    /**
     * Gets the value of the notification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the notification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNotification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link THTDeploymentConfig.Notification }
     * 
     * 
     */
    public List<THTDeploymentConfig.Notification> getNotification() {
        if (notification == null) {
            notification = new ArrayList<THTDeploymentConfig.Notification>();
        }
        return this.notification;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="publish" type="{http://wso2.org/ht/schema/deployment/config}tPublish"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}QName" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "publish"
    })
    public static class Notification {

        @XmlElement(required = true)
        protected TPublish publish;
        @XmlAttribute
        protected QName name;

        /**
         * Gets the value of the publish property.
         * 
         * @return
         *     possible object is
         *     {@link TPublish }
         *     
         */
        public TPublish getPublish() {
            return publish;
        }

        /**
         * Sets the value of the publish property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPublish }
         *     
         */
        public void setPublish(TPublish value) {
            this.publish = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link QName }
         *     
         */
        public QName getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link QName }
         *     
         */
        public void setName(QName value) {
            this.name = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="publish" type="{http://wso2.org/ht/schema/deployment/config}tPublish"/>
     *         &lt;element name="callback" type="{http://wso2.org/ht/schema/deployment/config}tCallback"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}QName" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "publish",
        "callback"
    })
    public static class Task {

        @XmlElement(required = true)
        protected TPublish publish;
        @XmlElement(required = true)
        protected TCallback callback;
        @XmlAttribute
        protected QName name;

        /**
         * Gets the value of the publish property.
         * 
         * @return
         *     possible object is
         *     {@link TPublish }
         *     
         */
        public TPublish getPublish() {
            return publish;
        }

        /**
         * Sets the value of the publish property.
         * 
         * @param value
         *     allowed object is
         *     {@link TPublish }
         *     
         */
        public void setPublish(TPublish value) {
            this.publish = value;
        }

        /**
         * Gets the value of the callback property.
         * 
         * @return
         *     possible object is
         *     {@link TCallback }
         *     
         */
        public TCallback getCallback() {
            return callback;
        }

        /**
         * Sets the value of the callback property.
         * 
         * @param value
         *     allowed object is
         *     {@link TCallback }
         *     
         */
        public void setCallback(TCallback value) {
            this.callback = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link QName }
         *     
         */
        public QName getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link QName }
         *     
         */
        public void setName(QName value) {
            this.name = value;
        }

    }

}
