//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.22 at 06:17:49 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(xmlns = { 
	      @javax.xml.bind.annotation.XmlNs(prefix = "htd", 
	                 namespaceURI="http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803")},namespace = "http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.oasis_open.docs.ns.bpel4people.ws_humantask._200803;
