//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.22 at 06:17:49 PM IST 
//


package org.wso2.developerstudio.humantask.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tCompletion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tCompletion">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803}tExtensibleElements">
 *       &lt;sequence>
 *         &lt;element name="condition" type="{http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803}tBoolean-expr"/>
 *         &lt;element name="result" type="{http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803}tResult" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tCompletion", propOrder = {
    "condition",
    "result"
})
public class TCompletion
    extends TExtensibleElements
{

    @XmlElement(required = true)
    protected TBooleanExpr condition;
    protected TResult result;

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link TBooleanExpr }
     *     
     */
    public TBooleanExpr getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBooleanExpr }
     *     
     */
    public void setCondition(TBooleanExpr value) {
        this.condition = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link TResult }
     *     
     */
    public TResult getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link TResult }
     *     
     */
    public void setResult(TResult value) {
        this.result = value;
    }

}
