//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.22 at 06:17:49 PM IST 
//


package org.wso2.developerstudio.humantask.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tReassignment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tReassignment">
 *   &lt;complexContent>
 *     &lt;extension base="{http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803}tExtensibleElements">
 *       &lt;sequence>
 *         &lt;element ref="{http://docs.oasis-open.org/ns/bpel4people/ws-humantask/200803}potentialOwners"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tReassignment", propOrder = {
    "potentialOwners"
})
public class TReassignment
    extends TExtensibleElements
{

    @XmlElement(required = true)
    protected TPotentialOwnerAssignment potentialOwners;

    /**
     * Gets the value of the potentialOwners property.
     * 
     * @return
     *     possible object is
     *     {@link TPotentialOwnerAssignment }
     *     
     */
    public TPotentialOwnerAssignment getPotentialOwners() {
        return potentialOwners;
    }

    /**
     * Sets the value of the potentialOwners property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPotentialOwnerAssignment }
     *     
     */
    public void setPotentialOwners(TPotentialOwnerAssignment value) {
        this.potentialOwners = value;
    }

}
